### PR TITLE
Addition of bismuth contamination properties

### PR DESCRIPTION
**Pull request by prisma34**
Implementation of the following correlations:

 Polonium activity coefficient by Joy, 1963.

 Iodine vapour pressure by Cubicciotti, 1959.

### CODE REVIEW

**Comment by prisma34** [comment]
The modifications suggested by @lelaus and @panDanieleN in the pull request #192 have been made here since since a lot of them were to be taken into account here too.

**Comment by lelaus** [comment]
The following modifications are suggested for properties related to Polonium:

- [ ] class `BismuthPoloniumActivityCoefficientJoy1963`:

1. to change the doc string from _Liquid lead *Polonium compound activity coeffcient* property class_ into _Liquid bismuth *dilute Polonium activity coefficient* property class_ since this property is related to the Polonium and since the related heavy liquid metal is the bismuth;
2. to change the doc string of the `correlation()` method by substituting _Polonium compound activity coefficient_ with _dilute Polonium activity coefficient_;
3. in analogy with other expressions of _lbh15_, to remove useless parentheses from the mathematical expression implemented in the method `correlation()`;
4. to change the string returned by the method `name()`, since this correlation is not related to _BiPo_ and there is no reason to add suffix `_a`; the returned name should inform that the current correlation is the activity coefficient of dilute Polonium contaminant;
5. to change the doc string of the method `range` from _Temperature validity range of the activity coefficient_ into _Temperature validity range of the dilute Polonium activity coefficient_;

- [ ] class `BismuthPoloniumActivityCoefficient`:

1. to change the doc string from _Liquid lead *Polonium compound activity coeffcient* property class_ into _Liquid bismuth *dilute Polonium activity coefficient* property class_ since this property is related to the Polonium and since the related heavy liquid metal is the bismuth;
2. to change the doc string of the `correlation()` method by substituting _Polonium compound activity coefficient_ with _dilute Polonium activity coefficient_;
3. in analogy with other expressions of _lbh15_, to remove useless parentheses from the mathematical expression implemented in the method `correlation()`;
4. to change the string returned by the method `name()`, since this correlation is not related to _BiPo_ and there is no reason to add suffix `_b`; the returned name should inform that the current correlation is the activity coefficient of dilute Polonium contaminant;
5. to change the doc string of the method `range` from _Temperature validity range of the activity coefficient_ into _Temperature validity range of the dilute Polonium activity coefficient_;

- [ ] since the classes `BismuthPoloniumActivityCoefficientJoy1963` and `BismuthPoloniumActivityCoefficient` provide 2 alternative correlations for the same property, in analogy with the approach already followed throughout _lbh15_, I'd suggest to implement an abstract class `BismuthPoloniumActivityCoefficientInterface` where to collect all the common methods, and to derive both from that.

**Comment by lelaus** [comment]
The following modifications are suggested for properties related to Iodine:

- [ ] class `BismuthIodineVapourPressureCubicciotti1959`:

1. in analogy with other expressions of _lbh15_, to remove useless parentheses from the mathematical expression implemented in the method `correlation()`;
2. to motivate why the melting-boiling temperatures have been chosen as range of validity of this property.

**Comment by lelaus** [comment]
I'd suggest to add the following property:

- [ ] eq. (5.55) for the caesium activity coefficient in liquid bismuth (range [T_m0, 1000]).

**Comment by prisma34** [comment]
Modifications suggested for `BismuthPoloniumActivityCoefficientJoy1963`, `BismuthPoloniumActivityCoefficient`, `BismuthIodineVapourPressureCubicciotti1959` and Caesium activity coefficient have been changed.

Creation of `BismuthPoloniumActivityCoefficientInterface` abstract class.

The gamma_BiPo from the Handbook has been defined as the correlation to use. The path `properties.bismuth_thermochemical_properties.bismuth_contamination` has been implemented in _properties_modules_list in order to not interfere with the tests.

**Comment by lelaus** [comment]
All the required modifications have been satisfactorily implemented.

**Pull request merged**
