### PR TITLE
Addition of lead contamination properties

### PR DESCRIPTION
**Pull request by prisma34**
Implementation of the following correlations:

 Polonium vapour pressure by Abakumov, 1994a.

 Polonium Henry constant by Ohno, 2006.

 Polonium activity coefficient by Li, 1998.

 Iodine vapour pressure by Konings, 1996.

 Iodine vapour pressure by Knacke, 1991.

 Caesium Henry constant by Yamshchikov, 2001.

 Caesium vapour pressure by Yamshchikov, 2001.

### CODE REVIEW

**Comment by lelaus** [comment]
- [ ] About correlation for vapour pressure by Abakumov, 1994a, please apply the following modifications:

1. to remove `Interface` from the name `LeadPoloniumVapourPressureInterfaceAbakumov1994a` since it could be misleading;
2. to change _Polonium compounds vapour pressure_ in _PbPo Polonium compound vapour pressure_ since this correlation refers only to _PbPo_;
3. to change _Vapour pressure of Polonium in pure lead_ into _Vapour pressure of PbPo compound in pure lead_ in `long_name()` method for the same reason as in the previous point;
4. to check and, if any, change all similar issues into all the doc strings of the class.

- [ ] in the HANDBOOK (p. 254), it is said that the activity coefficient of _PbPo_ can be reasonably approximated with the unity according to LI1998 and also IAEA2002. So I'd suggest to implement a dedicated property for the activity coefficient of _PbPo_ even if it is equal to 1.

- [ ] in the HANDBOOK (p. 254), it is said that the correlation of _P°_PbPo_ can be considered equal to that of the Henry constant, thus being usable for retrieving the value of _P_PbPo_ by multipling it by the molar ratio. So I'd suggest to implement a dedicated property for the Henry constant of _PbPo_; being equal to _P_PbPo_, no additional correlation should be implemented, but the already available one should be used;

- [ ] About correlation for Henry constant by Ohno, 2006: this correlation is only related to LBE, not to LEAD. To remove this correlation from the lead section, while evaluating its introduction into the LBE section.

- [ ] About correlation for the activity coefficient of Polonium by Li 1998, please apply the following modifications:
1. to remove `Interface` from the name `LeadPoloniumActivityCoefficientInterfaceLi1998` since it could be misleading;
2. to change _Polonium compounds activity coefficient_ in _PbPo Polonium compound activity coefficient_ since this correlation refers only to _PbPo_;
3. to change the name _gamma_Po_ into _gamma_PbPo_;
4. to change the `correlation_name` from _Li1998_ to _Abakumov1974a_ since both the correlations (5.14) and (5.16) it comes from are from Abakumov1974a;
5. to change the range of validity; the HANDBOOK says that this correlation (5.26) is obtained from correlations (5.14) and (5.16), whose ranges of application are [368, 604] °C and [640, 850] °C, respectively. The HANDBOOK suggests the range [913K, 1123K] for this correlation since it says (p.258): "Curve D is based on measurements performed above 913 K, and the extrapolation to 			  temperatures around 600 K can certainly not be trusted."). This is why the range of (5.16) is applied also to (5.26).

**Comment by prisma34** [comment]
I have made the modifications suggested by @lelaus review. I also deleted LeadPoloniumActivityCoefficientInterfaceLi1998 for the same reasons given for Henry constant by Ohno, 2006. The handbook gives the correlations for dilute lead and LBE solution, which do not correspond to the pure liquid lead environment.

**Comment by panDanieleN** [comment]
Looking at the commit 2d7255e, related to issue #184, `correlation` method is implemented using `10**X` to handle exponential function rather than `numpy.power(10, X)`. `correlation` shall safely handle arrays allowing element-wise evaluations (as previously addressed in #12).  Please consider to change all the implementation of this kind for all the heavy liquid metals.

**Comment by lelaus** [comment]
About correlations related to Iodine, please apply the following modifications:

- [ ] for class `LeadIodineVapourPressureKonings1996`:

1. change `name` from `P_PbI2_a` to `P_PbI2_s` since it seems more appropriate to relate to the solid form of _PbI2_;
2. correct `correlation_name` from `konings1994` to `konings1996`;
3. in the range, since the lower limit is the lead melting temperature, please substitute the value `600.6` with the corresponding variable defined in `_commons.py` module `LEAD_MELTING_TEMPERATURE`

- [ ] for class `LeadIodineVapourPressureKnacke1991`:

1. change `name` from `P_PbI2_b` to `P_PbI2_l` since it seems more appropriate to relate to the liquid form of _PbI2_;
2. in the range, since the upper limit is the lead boiling temperature, please substitute the value `2021.1` with the corresponding variable defined in `_commons.py` module `LEAD_BOILING_TEMPERATURE`;
3. in the range, substitute the lower limit value `697.1` with `697` since there are no overlapping problems with the range of `LeadIodineVapourPressureKonings1996`; it's up to the user to choose which correlation to use;

- [ ] for class `LeadIodineActivityCoefficientHandbook`:

1. in the range, since the limits are the lead melting and boiling temperatures, please substitute the values with the corresponding variables defined in `_commons.py` module;

- [ ] for class `LeadIodineHenryConstantKonings1996`:

1. change `name` from `K_PbI2_a` to `K_PbI2_s` since it seems more appropriate to relate to the solid form of _PbI2_;
2. in the range, since the lower limit is the lead melting temperature, please substitute the value `600.6` with the corresponding variable defined in `_commons.py` module `LEAD_MELTING_TEMPERATURE`

- [ ] for class `LeadIodineHenryConstantKnacke1991`:

1. change `name` from `K_PbI2_b` to `K_PbI2_l` since it seems more appropriate to relate to the liquid form of _PbI2_;
2. in the range, since the upper limit is the lead boiling temperature, please substitute the value `2021.1` with the corresponding variable defined in `_commons.py` module `LEAD_BOILING_TEMPERATURE`;
3.  in the range, substitute the lower limit value `697.1` with `697` since there are no overlapping problems with the range of `LeadIodineVapourPressureKonings1996`; it's up to the user to choose which correlation to use;

- [ ] for all the correlations suggested by the handbook, remove `Handbook` from the name of the corresponding class and assign `lbh15` as correlation_name.

**Comment by prisma34** [comment]
Modifications suggested by @panDanieleN have been made for all the classes of the module concerned by it. All the correlation methods have been tested, and all of them handle correctly array-like elements now.

**Comment by prisma34** [comment]
The modifications suggested by @lelaus have been made. The last suggestion has been respected for all the classes of the module concerned by it.

**Comment by lelaus** [comment]
About correlations related to caesium, please apply the following modifications:

- [ ] in class `LeadCaesiumHenryConstantYamshchikov2001`:

1. the correlation must be changed; the one that is implemented is related to the vapour pressure of pure metallic Caesium (5.51), while the Henry constant of Caesium in pure lead (5.54) must be implemented;

- [ ] in class `LeadCaesiumVapourPressureYamshchikov2001`:

1. remove _Yamshchikov2001_ since this correlation is retrieved from (5.3) and (5.4);
2. change `correlation_name` into `lbh15`.

**Comment by prisma34** [comment]
The modifications suggested by @lelaus concerning Caesium intermetallic compounds have been made.

**Comment by lelaus** [comment]
Please, be sure that quality checks with `pycodestyle` and `pylint` are passed satisfactorily.

**Review by lelaus — APPROVED** [review]

**Comment by lelaus** [comment]
Since the classes `LeadIodineVapourPressureKonings1996` and `LeadIodineVapourPressureKnacke1991` provide 2 alternative correlations for the same property, in analogy with the approach already followed throughout _lbh15_, I'd suggest to implement an abstract class `LeadIodineVapourPressureInterface` where to collect all the common methods, and to derive both from that.

The same goes also for the classes `LeadIodineHenryConstantKonings1996` and `LeadIodineHenryConstantKnacke1991`: an abstract class named `LeadIodineHenryConstantInterface` is suggested to be implemented which to derive the first two from.

**Comment by prisma34** [comment]
Implementation of `LeadIodineVapourPressureInterface` and derivation of `LeadIodineVapourPressureKonings1996` and `LeadIodineVapourPressureKnacke1991` from it, as suggested by @lelaus.

Same goes for `LeadIodineHenryConstantInterface`, with `LeadIodineHenryConstantKonings1996` and `LeadIodineHenryConstantKnacke1991`.

**Comment by lelaus** [comment]
What implemented in 8939eb4 replies to the required modifications.
The indication of the correlations to use by default for Iodine vapour pressure and Henry constant is still missing.

**Review by panDanieleN — APPROVED** [review]

**Comment by prisma34** [comment]
As suggested byb @lelaus, the P_PbI2 and K_PbI2 from knacke1991 have been defined as the correlations to use. The path `properties.lead_thermochemical_properties.lead_contamination` has been implemented in _properties_modules_list in order to not interfere with the tests.

**Comment by lelaus** [comment]
All the required modifications have been satisfactorily implemented.

**Pull request merged**
